alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gl='git log --oneline --decorate --graph'
alias gla='git log --oneline --decorate --graph --all'
alias gld='git log --pretty=format:"%h %ad %s" --graph --all'
alias glr='git log --pretty=format:"%h %ar %s" --graph --all'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias lb='lsblk -o PATH,LABEL,FSTYPE,UUID,MOUNTPOINT'
alias suspend='sudo systemctl suspend'
