#!/bin/bash
# script to build config.tar.xz after an update
# must be run in /home/robert/configdata
cd /home/robert
tar --xz -cvf config.tar.xz .bash_aliases .config .gitconfig .git-credentials .psensor
