#!/bin/bash
# script to build config.tar.xz after an update
# must be run in /home/robert/configdata
cd /home/robert
tar --xz -C /home/robert -cvf config.tar.xz .config/ubuntu-mate .config/geany .config/dconf .config/gh .config/rclone .gitconfig .git-credentials .psensor
