#!/bin/sh
##################################################
# configdata:postinst
##################################################

# xz-utils is required for untarring
# this package is installed with dpkg -i configdata
#pre-depends xz-utils does not work
# apt install also does not work here

# postinstall sets mode of /etc/sudoers.d/robert
# to -r-r-----
chmod 0440 /etc/sudoers.d/robert
chown root:root /etc/sudoers.d/robert

# /home/robert/config.tar.xz is archived because
# some of the config files contain tokens for a login.
# github detects these tokens and disables them.
# the archive hides these tokens.
# /home/robert/config.tar.xz must be extracted
cd /home/robert
sudo -u robert tar --xz -xvf config.tar.xz


# remove config.tar.xz
# rm /home/robert/config.tar.xz

# rem build and xtract
# rm /home/robert/build
# rm /home/robert/xtract

# copy /tmp/grub to /etc/default/
# first make a backup of /etc/default/grub
# if one does not exist
if test -f "/etc/default/grub.bak"; then
	# /etc/default/grub.bak does exist
	echo "configdata:postinst /etc/default/grub.bak does exist";
	cp -v /tmp/grub /etc/default/
else
	# /etc/default/grub.bak does not exist
	echo "configdata:postinst /etc/default/grub.bak does not exist";

	if test -f "/etc/default/grub"; then
		# /etc/default/grub does exist and /etc/default/grub.bak does not exist
		echo "configdata:postinst /etc/default/grub does exist"
		mv -fv /etc/default/grub /etc/default/grub.bak
		cp -v /tmp/grub /etc/default/
	else
		# /etc/default/grub and /etc/default/grub.bak do not exist
		echo "configdata:postinst /etc/default/grub does not exist"
		# grub and grub.bak do not exist
		# make both
		cp -v /tmp/grub /etc/default/
		cp -v /etc/default/grub /etc/default/grub.bak
	fi
fi

# setup default console with Terminus
cd /etc/default
# make a backup if it does not exist

test -f /etc/default/console-setup.bak || cp -v /etc/default/console-setup /etc/default/console-setup.bak

# edit console-setup to set fonts
/usr/local/bin/stedit.pl -f /etc/default/console-setup -s /FONTFACE=.*/FONTFACE="Terminus"/ -s /FONTSIZE=.*/FONTSIZE="14x28"/ -o -w;

# implement the new fontsize
setupcon -f
setupcon --save

# update-grub must not be run in the live system or in the chroot environment
# if init-linux is run on the live desktop then update-grub
# must be prevented from running
# this section of code only runs on a desktop , not the livesystem

test `hostname` = "live" || update-grub
