#!/bin/bash
# the grub backup file must be restored

# for testing
if test -f "/etc/default/grub.bak" ; then
	echo "/etc/default/grub.bak exists";
	mv -fv "/etc/default/grub.bak" "/etc/default/grub"
else
	echo "/etc/default/grub.bak does not exist";
fi
